artifact_location: /Users/darius/Documents/projects/building_crack_object_detection/runs/mlflow/357122613073641870
creation_time: 1718447463558
experiment_id: '357122613073641870'
last_update_time: 1718447463558
lifecycle_stage: active
name: /Shared/YOLOv8
