artifact_location: /Users/darius/Documents/projects/building_crack_object_detection/runs/mlflow/443695743821051668
creation_time: 1718448240070
experiment_id: '443695743821051668'
last_update_time: 1718448240070
lifecycle_stage: active
name: Yolov8CrashDetection
