artifact_location: /Users/darius/Documents/projects/building_crack_object_detection/runs/mlflow/0
creation_time: 1718447463553
experiment_id: '0'
last_update_time: 1718447463553
lifecycle_stage: active
name: Default
